name: Continuous Deployment to Test Environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      # Add steps to build your application

      - name: Deploy to Test Environment
        run: |
          chmod +x ./gradlew
          ./gradlew build deploy -Penv=test
        env:
          ENVIRONMENT: test
          DATABASE_URL: "localhost:3311/rezeptbuch"

      - name: Run tests in Test Environment
        run: |
          # Add commands to run tests in the test environment
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          # Add other environment-specific variables