name: Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: rezeptbuch
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - "3311:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build Backend
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Test Backend
        run: |
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew test
